#############################################
# milss/tradercppbuild:v1.6
# Build container for tradercpp
# Published to dockerhub in order to accelerate github actions
# Uses:
#  - Ubuntu 24.04
#  - CMake 4
#  - Conan 2 (incl. Python3)
#  - GCC 13
#  - LLVM 18 (clang-format and clang-tidy)
#  - make
#  - ninja-build
#  - perl (compilation dependency for conan packages)
#  - coverage (lcov, gcovr)
#############################################


FROM ubuntu:24.04 AS build_container

# Set noninteractive mode to avoid prompts during install
ENV DEBIAN_FRONTEND=noninteractive


# Install CMake 4
ARG CMAKE_VERSION=4.1.2-0kitware1ubuntu24.04.1

RUN apt update && apt install -y --no-install-recommends \
    ca-certificates \
    gnupg \
    lsb-release \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | \
    gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null && \
    echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" | \
    tee /etc/apt/sources.list.d/kitware.list >/dev/null

RUN apt update && apt install -y --no-install-recommends \
    cmake=${CMAKE_VERSION} \
    && rm -rf /var/lib/apt/lists/*


# Install GCC 13
RUN apt update && apt install -y --no-install-recommends \
    software-properties-common && \
    add-apt-repository ppa:ubuntu-toolchain-r/test -y && \
    apt update && apt install -y --no-install-recommends \
    g++-13 \
    gcc-13 \
    && rm -rf /var/lib/apt/lists/*


# Install LLVM 18 (clang-format and clang-tidy)
RUN apt update && apt install -y --no-install-recommends \
    gnupg \
    lsb-release \
    software-properties-common \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -

RUN echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main" > /etc/apt/sources.list.d/llvm18.list

RUN apt update && apt install -y --no-install-recommends \
    clang-format-18 \
    clang-tidy-18 \
    && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-18 100 && \
    update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-18 100


# Install Conan 2 (and profile)
ARG CONAN_VERSION=2.19.1

RUN apt update && apt install -y --no-install-recommends \
    python3 python3-pip python3-venv \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /opt/conan-venv && \
    /opt/conan-venv/bin/pip install --upgrade pip && \
    /opt/conan-venv/bin/pip install gcovr && \
    /opt/conan-venv/bin/pip install "conan==${CONAN_VERSION}"
# TODO: --no-cache-dir

ENV PATH="/opt/conan-venv/bin:$PATH"

RUN mkdir -p /root/.conan2/profiles && printf \
    "[settings]\n\
    arch=x86_64\n\
    build_type=Release\n\
    compiler=gcc\n\
    compiler.cppstd=gnu23\n\
    compiler.libcxx=libstdc++11\n\
    compiler.version=13\n\
    os=Linux\n" \
    > /root/.conan2/profiles/default


# Install build tools
RUN apt update && apt install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    lcov \
    make \
    ninja-build \
    perl \
    unzip \
    && rm -rf /var/lib/apt/lists/*
