#!/bin/bash

################################################################
# pre-commit.sh
# Fails the commit on any linting/formatting errors.
# NB: file paths are relative to the script location,
# so the script can be executed from any path
################################################################

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Run subscripts

echo "Running strict pre-commit checks (clang-tidy, clang-format, build-debug)..."

# TODO(mils): does this also need to be converted to:
# `git diff -U0 origin/master...HEAD -- '*.cpp'`
git diff -U0 master...HEAD -- '*.cpp' | \
  clang-tidy-diff-18.py -p1 -path "$DIR/../build/Debug"

bash "$DIR/check_clang_format.sh"

make build-debug

echo "✅ Pre-commit checks passed on full codebase."
