name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build tools
        run: |
          sudo apt update && sudo apt install -y g++
          pip install conan

      - name: Build
        run: |
          conan install . --build=missing -s build_type=Release && \
          cmake --preset Release && \
          cmake --build --preset Release

      - name: Run
        run: ./build/Release/tradercpp
