name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Conan
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.*') }}
          restore-keys: |
            ${{ runner.os }}-conan-
      
      - name: Set up build tools
        run: |
          sudo apt update && sudo apt install -y g++
          pip install conan
          conan profile detect --force

      - name: Build
        run: |
          conan install . --build=missing -s build_type=Debug
          cmake --preset=conan-debug
          cmake --build --preset=conan-debug

      - name: Test
        run: |
          ctest --test-dir build/Debug --output-on-failure
