name: Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual run from GitHub UI

jobs:
  call-reusable:
    uses: ./.github/workflows/clean_build_test.yml
    with:
      ref: ${{ 'master' }}
